# Generated by Django 3.2 on 2021-05-04 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rating', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Casts',
            new_name='Cast',
        ),
        migrations.RenameModel(
            old_name='Directors',
            new_name='Director',
        ),
        migrations.RenameModel(
            old_name='Languages',
            new_name='Language',
        ),
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
        migrations.RenameModel(
            old_name='Movie_Images',
            new_name='Movie_Image',
        ),
        migrations.RenameModel(
            old_name='Movie_Videos',
            new_name='Movie_Video',
        ),
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RenameModel(
            old_name='Stars',
            new_name='Star',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameModel(
            old_name='Writers',
            new_name='Writer',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='language_name',
        ),
    ]
