# Generated by Django 3.2 on 2021-05-04 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rating', '0002_auto_20210504_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cast_ids',
        ),
    ]
