# Generated by Django 3.2.1 on 2021-05-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rating', '0003_remove_movie_cast_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
